backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: assets/images
public_folder: img

collections:
  - name: "home"
    label: "Pages"
    extension: "json"
    format: "json"
    folder: data/home
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { name: title }
      - { name: title2 }
      - { name: title3 }
      - { name: desc }
      - { name: button }