backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: assets/images
public_folder: img

collections:
  - name: "home"
    label: "Home"
    extension: "json"
    format: "json"
    folder: data/home
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { name: title }
      - { name: title2 }
      - { name: title3 }
      - { name: desc }
      - { name: button }
collections:
  - name: "services"
    label: "Services"
    extension: "json"
    format: "json"
    folder: data/services
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { name: title }
      - { name: desc }
      - { name: cards }
collections:
  - name: "solution"
    label: "Solutions"
    extension: "json"
    format: "json"
    folder: data/solution
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { name: title }
      - { name: desc }
      - { name: infos }
collections:
  - name: "footer"
    label: "Footer"
    extension: "json"
    format: "json"
    folder: data/services
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { name: text1 }
      - { name: text2 }
collections:
  - name: "contact"
    label: "Contact"
    extension: "json"
    format: "json"
    folder: data/contact
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { name: title }
      - { name: desc }
      - { name: input }
      - { name: button }